main_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup', views.signup, name='signup'),
    path('destinations/search/', views.destinations, name = "destination_search"),
    path('<int:trip_id>/<airport_code>/hotels/', views.hotel_search, name = "hotel_search"), 
    path('<int:trip_id>/<airport_code>/flights/', views.flight_search, name = "flight_search"),
    path('<int:trip_id>/<airport_code>/flights/add/', views.flight_add, name = "flight_add"),
    path('<int:trip_id>/<airport_code>/hotels/add/', views.hotel_add, name = "hotel_add"),
    path('trips/', views.trip_list, name='view_trips'),
    path('trips/create/', views.CreateTrip.as_view(), name="create_trip"),
    path('trips/<int:trip_id>/<airport_code>/', views.trips_detail, name="detail"),
    path('trips/<int:pk>/<airport_code>/delete/', views.TripDelete.as_view(), name='delete_trip'),
    path('trips/<int:pk>/<airport_code>/edit/', views.TripEdit.as_view(), name='edit_trip'),
    path('profile/trip/', views.SaveTrip, name="save_trip"),
    path('trips/<int:trip_id>/<airport_code>/add_luggage_items/', views.add_luggage_items, name="add_luggage_items"),
    path('trips/<int:trip_id>/<airport_code>/<int:item_id>/add/', views.add, name = "add_luggage_quantity"),
    path('trips/<int:trip_id>/<airport_code>/<int:item_id>/subtract/', views.subtract, name = "subtract_luggage_quantity")
]

vagary/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    
]

main_app/models.py
from django.db import models
from djmoney.models.fields import MoneyField
from django.contrib.auth.models import User
from django.urls import reverse
import urllib3
import xml
import datetime


# Create your models here.

class Trip(models.Model):
    name = models.CharField(max_length = 250, default = 'My Trip')
    budget = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    origin = models.CharField(max_length = 3, default = 'LAX')

    def __str__(self):
        return f"budget: ${self.budget}"

    def get_absolute_url(self):
        return reverse('detail', kwargs={'trip_id': self.id, 'airport_code': self.origin})

class Hotel(models.Model):
    name = models.CharField(max_length = 250)
    address = models.CharField(max_length = 250)
    check_in = models.CharField(max_length = 100)
    check_out = models.CharField(max_length = 100)
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    price = models.FloatField()
    
    def __str__(self):
        return f"{self.name} // {self.price}"

class Flight(models.Model):
    departure_date = models.DateField()
    origin = models.CharField(max_length = 3, default = 'LAX')
    destination = models.CharField(max_length = 3, default = 'LAX')
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    price = models.FloatField()
    
    def __str__(self):
        return f"Depart Date: {self.departure_date}, Price: {self.price}, Origin: {self.origin}, Destination: {self.destination}"

class Suitcase(models.Model):
    item_name = models.CharField(max_length = 100)
    quantity = models.IntegerField(default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main_app/forms.py
from django.forms import ModelForm
from .models import Suitcase

class LuggageForm(ModelForm):
    class Meta:
        model = Suitcase
        fields = ['item_name', 'quantity']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from amadeus import Client, ResponseError
from amadeus.client.decorator import Decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.contrib.auth import authenticate, login
import os
import requests
from datetime import datetime, date
from .models import Trip, Hotel, Flight, User, Suitcase
from .forms import LuggageForm

# Create your views here.
amadeus = Client(
    client_id=os.environ.get("AMADEUS_CLIENT_ID"),
    client_secret=os.environ.get("AMADEUS_CLIENT_SECRET")
)
data = requests.get("http://iatacodes.org/api/v6/cities?api_key=c05152c1-441f-430e-9c6c-54dca70f1427")
res = data.json()['response']


def home(request):
    return render(request, 'home.html')


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in via code
            login(request, user)
            return redirect('home')
        else:
            error_message = 'Invalid credentials - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

def destinations(request):
    origin = request.POST.get('origin')
    d_date = request.POST.get('d_date')
    budget = float(request.POST.get('budget'))

    check_date = datetime.strptime(d_date, '%Y-%m-%d').date()
    
    if request.user.is_authenticated:
        trip = Trip(budget=budget, user=request.user, origin=origin)
        trip.save()
    else:
        return redirect('login')
    
    if check_date < date.today():
       return redirect('home')

    try:
        search_list = amadeus.shopping.flight_destinations.get(
            origin=origin,
            departureDate=d_date
            ).data
        destinations = []
        for destination in search_list:
            d_price = float(destination['price']['total'])
            if d_price <= budget/2:
                destinations.append(destination)
        return render(request, 'destinations/search.html', {
        'destinations': destinations, 
        'budget': budget, 'origin': origin, 
        'departure_date':d_date, 
        "trip": trip,
        'iata': res
        })
    except: 
        return render (request, 'error.html')

def hotel_search(request, trip_id, airport_code):
    budget = float(request.POST.get('budget'))
    trip = Trip.objects.get(id=trip_id)
    hotel_search = amadeus.shopping.hotel_offers.get(cityCode=airport_code).data

    hotels = []
    for hotel in hotel_search:
        h_price = float(hotel['offers'][0]['price']['total'])
        if h_price <= budget/3:
            hotels.append(hotel) 
    return render(request, 'hotels/search.html', {'hotels' : hotels, 'trip': trip, 'airport_code': airport_code})

def flight_search(request, trip_id, airport_code):
    budget = float(request.POST.get('budget'))
    origin = request.POST.get('origin')
    departure_date = request.POST.get('departure_date') or request.POST.get('return_date')
    trip = Trip.objects.get(id=trip_id)


    flight_search = amadeus.shopping.flight_offers.get(destination=airport_code, origin=origin, departureDate=departure_date).data
    flights = []
    for flight in flight_search:
        f_price = float(flight['offerItems'][0]['price']['total'])
        f_origin = flight['offerItems'][0]['services'][0]['segments'][0]['flightSegment']['departure']['iataCode']
        f_destination = flight['offerItems'][0]['services'][0]['segments'][0]['flightSegment']['arrival']['iataCode']
        if f_price <= budget/3 and f_origin == origin and f_destination == airport_code:
            flights.append(flight)
    return render(request, 'flights/search.html', {
        'flights': flights, 
        'trip': trip, 
        'departure_date': departure_date, 
        'airport_code': airport_code,
        'iata': res
        })

def flight_add(request, trip_id, airport_code):
    price = request.POST.get('price')
    trip = Trip.objects.get(id=trip_id)
    origin = request.POST.get('origin')
    destination = request.POST.get('destination')
    departure_date = request.POST.get('departure_date')
    airport_code = airport_code
        
    current_flight = Flight.objects.create(
        departure_date = departure_date,
        destination = destination,
        price = price,
        origin = origin,
        trip = trip,
        )
    if trip.origin == airport_code:
        return redirect(f'/trips/{trip.id}/{airport_code}')
    else: 
        return redirect(f'/trips/{trip.id}/{origin}')

def hotel_add(request, trip_id, airport_code):
    price = request.POST.get('price')
    name = request.POST.get('name')
    check_out = request.POST.get('check_out')
    check_in = request.POST.get('check_in')
    street = request.POST.get('street')
    city = request.POST.get('city')
    trip = Trip.objects.get(id=trip_id)
    origin = airport_code

    current_hotel = Hotel.objects.create(
        name = name,
        check_out = check_out,
        check_in = check_in, 
        address = street + city,
        price = price,
        trip = trip
        )

    print(current_hotel.trip)
    
    return redirect(f'/trips/{trip.id}/{origin}')

class CreateTrip(LoginRequiredMixin, CreateView):
    model = Trip
    fields = ['name', 'budget', 'origin']
    def form_valid(self, form):
        form.instance.user = self.request.user   # Let the CreateView do its job as usual
        return super().form_valid(form)

def trips_detail(request, trip_id, airport_code):
    trip = Trip.objects.get(id=trip_id)

    if airport_code == trip.origin: 
        origin = airport_code
    else: 
        origin = trip.origin
    
    try:
        depart_flight = Flight.objects.get(trip=trip, origin=origin)
    except:
        depart_flight = None

    try: 
        return_flight = Flight.objects.get(trip=trip, destination=origin)
    except:
        return_flight = None

    try:
        hotel = Hotel.objects.get(trip=trip)
    except:
        hotel = None
    
    try: 
        trip_days = (return_flight.departure_date - depart_flight.departure_date).days
        trip_nights = trip_days - 1
        total_tops = trip_days + 2
        total_bottoms = trip_days - 1
        total_socks = trip_days + 3
        total_undergarments = trip_days + 3
    except: 
        trip_days = None
        trip_nights = None
        total_tops = None
        total_bottoms = None
        total_socks = None
        total_undergarments = None

    if depart_flight and return_flight and hotel:
       hotel.price = hotel.price * trip_days

    luggage_form = LuggageForm()

    return render(request, 'trips/detail.html', {
        'trip': trip,
        'hotel': hotel,
        'depart_flight': depart_flight, 
        'return_flight': return_flight,
        'iata': res,
        'luggage_form': luggage_form,
        'trip_days': trip_days,
        'trip_nights': trip_nights,
        'total_tops': total_tops,
        'total_bottoms': total_bottoms, 
        'total_socks': total_socks, 
        'total_undergarments': total_undergarments,
    })

def trip_list(request):
    trip = Trip.objects.filter(user=request.user)
    return render(request, 'main_app/trip_list.html', {'trip_list': trip, 'iata': res})


class TripDelete(DeleteView):
    model = Trip
    success_url = '/trips/'

class TripEdit(UpdateView):
    model = Trip
    fields = ['name', 'budget']

def SaveTrip(request):
    form = request.POST
    print(form)

def add_luggage_items(request, trip_id, airport_code):
    form = LuggageForm(request.POST)
    item = request.POST.get('item_name')
    print(item)

    if Suitcase.objects.filter(item_name=item).exists():
        print('item exists')
        return redirect('detail', trip_id = trip_id, airport_code=airport_code)
    else: 
        if form.is_valid():
            new_luggage = form.save(commit=False)
            new_luggage.user = request.user
            new_luggage.save()
            print(new_luggage)
        return redirect('detail', trip_id=trip_id, airport_code=airport_code)

def add(request, trip_id, airport_code, item_id):
    item = Suitcase.objects.get(id = item_id)
    item.quantity = item.quantity + 1
    item.save()
    return redirect('detail', trip_id=trip_id, airport_code=airport_code)

def subtract(request, trip_id, airport_code, item_id):
    item = Suitcase.objects.get(id = item_id)
    item.quantity = item.quantity - 1

    if item.quantity == 0:
        item.delete()
    else:
        item.save()
    return redirect('detail', trip_id=trip_id, airport_code=airport_code)

main_app/templates/trips/detail.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block body%}

<body>
    {% endblock %}
    {% block content %}
<div class = "row">
    <div class="col-6">
        <div class="card-body text-center">
            <h1 class="card-header trip-header">{{trip.name}}</h1>
            <br>
            <!-- {% if depart_flight %} -->
            <div class='row'>
                <div class='col-6'>
                    {% for i in iata %}
                    {% if i.code == depart_flight.destination %}
                    <h4>Flight to {{i.name}}</h4>
                    {%endif%}
                    {%endfor%}
                    <h5>{{depart_flight.departure_date}} from {{depart_flight.origin}}</h5>
                </div>
                <div class='col-6'>
                    <h4>Price</h4>
                    <h5>${{depart_flight.price|floatformat:2}}</h5>
                </div>
            </div>
            <div class='row'>
                {% if return_flight %}
                <div class='col-6'>
                    {% for i in iata %}
                    {% if i.code == return_flight.destination %}
                    <h4>Flight to {{i.name}}</h4>
                    {%endif%}
                    {%endfor%}
                    <h5>{{return_flight.departure_date}} from {{return_flight.origin}}</h5>
                </div>
                <div class='col-6'>
                    <h4>Price</h4>
                    <h5>${{return_flight.price|floatformat:2}}</h5>
                </div>
                {% else %}
                <div class='col-12 text-center'>
                    <form action="/{{trip.id}}/{{depart_flight.origin}}/flights/" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="budget" value="{{trip.budget}}">
                        <input type="hidden" name="origin" value="{{depart_flight.destination}}">
                        <input type="date" class="form-control" name="return_date" aria-describedby="basic-addon1"
                            required>
                        <input type="submit" value="Add Returning Flight" class="btn btn-light">
                    </form>
                </div>
                {% endif %}
            </div>
            <div class='row'>
                {% if hotel %}
                <div class="col-6">
                    <h4>Hotel</h4>
                    <h5 class="text-left">{{hotel.name}}</h5>
                    <p class="text-left">{{hotel.address}}</p>
                </div>
                <div class='col-6'>
                    <h4>Price</h4>
                    <h5>${{hotel.price|floatformat:2}}</h5>
                </div>
                {% else %}
                <div class='col-12 text-center'>
                    <form action="/{{trip.id}}/{{depart_flight.destination}}/hotels/" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="budget" value="{{trip.budget}}">
                        <input type="submit" value="Add Hotel" class="btn btn-light">
                    </form>
                    {% endif %}
                </div>
            </div>
            <br>
            <hr>
            <div class="row">
                <div class="col-4">
                    <h4>Budget</h4>
                    <h5>${{trip.budget}}</h5>
                </div>
                <div class="col-4">
                    <h4>Current Total</h4>
                    {%if not return_flight and not hotel%}
                    <h5> ${{depart_flight.price|floatformat:2}}</h5>
                    {%endif%}
                    {%if return_flight and not hotel%}
                    <h5> ${{depart_flight.price|add:return_flight.price|floatformat:2}}</h5>
                    {%endif%}
                    {%if return_flight and hotel %}
                    <h5>${{depart_flight.price|add:return_flight.price|add:hotel.price|floatformat:2}}</h5>
                    {%endif%}
                </div>
                <div class="col-4">
                    <h4>Remaining Balance</h4>
                    {%if not return_flight and not hotel%}
                    <h5> ${{trip.budget|sub:depart_flight.price|floatformat:2}}</h5>
                    {%endif%}
                    {%if return_flight and not hotel%}
                    <h5> ${{trip.budget|sub:depart_flight.price|sub:return_flight.price|floatformat:2}}</h5>
                    {%endif%}
                    {%if return_flight and hotel %}
                    <h5>${{trip.budget|sub:depart_flight.price|sub:return_flight.price|sub:hotel.price|floatformat:2}}
                    </h5>
                    {%endif%}
                </div>
            </div>
            <a href="{% url 'delete_trip' trip.id depart_flight.origin %}" class="btn btn-light col-12">Delete Trip</a>
            <a href="{% url 'edit_trip' trip.id depart_flight.origin%}" class="btn btn-light col-12">Edit Trip</a>
        </div>
    </div>
    <div class = "col-4">
        <h4 class = 'text-center'>Get Packing!</h4>
        {% if trip_days != None %}
        <h4 class = 'text-center'>{{trip_days}} Days & {{trip_nights}} Nights</h4>
        {% endif %}
        <p class = 'card-header text-center'> Clothes </p>
        <ul>
            {% if trip_days != None %}
                <li>{{total_tops}} tops</li>
                <li>{{total_bottoms}} bottoms</li>
                <li>{{total_socks}} socks</li>
                <li>{{total_undergarments}} undergarments</li>
                {% for item in user.suitcase_set.all %}
                    {% if item.quantity != 0%}
                    <li>{{item.quantity}} {{item.item_name}}</li><a class = "btn btn-light" href = "{% url 'add_luggage_quantity' trip.id trip.origin item.id %}">+</a><a class = 'btn btn-light' href = "{% url 'subtract_luggage_quantity' trip.id trip.origin item.id %}">-</a>
                {% endif %}
                {% endfor %}
                <form action="/trips/{{trip.id}}/{{trip.origin}}/add_luggage_items/" method="POST">
                    {% csrf_token %}
                    {{luggage_form.as_p}}
                    <input type="submit" value="Add Items">
                </form>
            {% else %}
                <p>Add a Return Flight to generate a suggested clothing packing list!</p>
            {% endif %}
        </ul>
        <p class = 'card-header text-center'>Toiletries</p>
        <ul>
            <li>Toothbrush</li>
            <li>Toothpaste</li>
            <li>Floss</li>
            <li>Face wash</li>
            <li>Shampoo</li>
            <li>Conditioner</li>
            <li>Body wash</li>
            <li>Deodorant</li>
            <li>Razor</li>
            <li>Lotion</li>
            <li>Medications</li>
        </ul>
        <p class = 'card-header text-center'>For the Plane</p>
        <ul>
            <li>Driver's License</li>
            <li>Passport</li>
            <li>Wallet</li>
            <li>Laptop + charger</li>
            <li>Phone + charger</li>
            <li>Tablet + charger</li>
            <li>Headphones</li>
            <li>Pillow</li>
        </ul>
    </div>
</div>


    {% endblock %}
    {% block footer %}
    <div class="card-footer text-muted">
        {% endblock %}